//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocachingTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeocachingTool.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Geocaching Backpack.
        /// </summary>
        internal static string aboutPageHeader {
            get {
                return ResourceManager.GetString("aboutPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocaching Backpack is developed and maintained by Finn Alberts. Problems can be reported at www.finnalberts.nl/contact..
        /// </summary>
        internal static string aboutPageParagraph1 {
            get {
                return ResourceManager.GetString("aboutPageParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocaching is a game where you search the real world for so called &apos;caches&apos;. Geocaching is property of Groundspeak Incorporated. More information at www.geocaching.com..
        /// </summary>
        internal static string aboutPageParagraph2 {
            get {
                return ResourceManager.GetString("aboutPageParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used icons are property of Font Awesome and are used under the CCA 4.0 license. More information at www.fontawesome.com/license..
        /// </summary>
        internal static string aboutPageParagraph3 {
            get {
                return ResourceManager.GetString("aboutPageParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more at .
        /// </summary>
        internal static string aboutPageReadMore {
            get {
                return ResourceManager.GetString("aboutPageReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string aboutPageTitle {
            get {
                return ResourceManager.GetString("aboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string aboutPageVersion {
            get {
                return ResourceManager.GetString("aboutPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this? This action cannot be reversed..
        /// </summary>
        internal static string areYouSureDelete {
            get {
                return ResourceManager.GetString("areYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of cache.
        /// </summary>
        internal static string cachename {
            get {
                return ResourceManager.GetString("cachename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string calculate {
            get {
                return ResourceManager.GetString("calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner in degrees.
        /// </summary>
        internal static string calculateProjectionPageAngle {
            get {
                return ResourceManager.GetString("calculateProjectionPageAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance in meters.
        /// </summary>
        internal static string calculateProjectionPageDistance {
            get {
                return ResourceManager.GetString("calculateProjectionPageDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate projection.
        /// </summary>
        internal static string calculateProjectionPageTitle {
            get {
                return ResourceManager.GetString("calculateProjectionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string compassPageDisclaimer {
            get {
                return ResourceManager.GetString("compassPageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the accuracy of the compass and distance is strongly dependend on your device. Your location will be updated approximately every 15 seconds and will be accurate to about 10 meters. This also depends on your device. Remember this while caching..
        /// </summary>
        internal static string compassPageDisclaimerText {
            get {
                return ResourceManager.GetString("compassPageDisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location could not be determined..
        /// </summary>
        internal static string compassPageNoLocation {
            get {
                return ResourceManager.GetString("compassPageNoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set target.
        /// </summary>
        internal static string compassPageSetTarget {
            get {
                return ResourceManager.GetString("compassPageSetTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        internal static string compassPageTitle {
            get {
                return ResourceManager.GetString("compassPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string convert {
            get {
                return ResourceManager.GetString("convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert coordinates.
        /// </summary>
        internal static string coordinatePageTitle {
            get {
                return ResourceManager.GetString("coordinatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM to DD.
        /// </summary>
        internal static string ddmToDd {
            get {
                return ResourceManager.GetString("ddmToDd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD to DDM.
        /// </summary>
        internal static string ddToDdm {
            get {
                return ResourceManager.GetString("ddToDdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string east {
            get {
                return ResourceManager.GetString("east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location on your device is not enabled..
        /// </summary>
        internal static string errorCompassLocationOff {
            get {
                return ResourceManager.GetString("errorCompassLocationOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For using the compass your location is required..
        /// </summary>
        internal static string errorCompassNoPermission {
            get {
                return ResourceManager.GetString("errorCompassNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately your device does not support compass functionality..
        /// </summary>
        internal static string errorCompassNoSupport {
            get {
                return ResourceManager.GetString("errorCompassNoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        internal static string errorDefault {
            get {
                return ResourceManager.GetString("errorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This letter already exists. Use a different letter..
        /// </summary>
        internal static string errorLetterAlreadyExists {
            get {
                return ResourceManager.GetString("errorLetterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all letters.
        /// </summary>
        internal static string formulaPageDeleteAllLetters {
            get {
                return ResourceManager.GetString("formulaPageDeleteAllLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add letters by tapping &apos;new&apos;. Give each letter a value and save it. The letter will now appear in the overview. From the overview you can also edit or delete a letter.
        ///
        ///In the top of the screen you can enter calculations to calculate a value. These calculations can be simple like 5+5, but they may also contain letters you added. You can use +, -, * and /.
        ///
        ///Example: you added the letter &apos;a&apos; with a value of 4. By entering 10-a you will have a result of 6..
        /// </summary>
        internal static string formulaPageHelp {
            get {
                return ResourceManager.GetString("formulaPageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string formulaPageLetter {
            get {
                return ResourceManager.GetString("formulaPageLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values of letters.
        /// </summary>
        internal static string formulaPageLetterValues {
            get {
                return ResourceManager.GetString("formulaPageLetterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no letters yet. Save a new letter by tapping &apos;new&apos; in the upper right corner..
        /// </summary>
        internal static string formulaPageNoLetters {
            get {
                return ResourceManager.GetString("formulaPageNoLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate formula.
        /// </summary>
        internal static string formulaPageTitle {
            get {
                return ResourceManager.GetString("formulaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This backpack contains all the tools you&apos;ll need while searching for Geocaches. Quickly find the word value, calculate the next coordinate and save all important information for finding the cache..
        /// </summary>
        internal static string mainPageDescription {
            get {
                return ResourceManager.GetString("mainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore and search for some caches!.
        /// </summary>
        internal static string mainPageHeader {
            get {
                return ResourceManager.GetString("mainPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string mainPageTitle {
            get {
                return ResourceManager.GetString("mainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Geocaching Backpack!.
        /// </summary>
        internal static string mainPageWelcome {
            get {
                return ResourceManager.GetString("mainPageWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meter.
        /// </summary>
        internal static string meter {
            get {
                return ResourceManager.GetString("meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string newText {
            get {
                return ResourceManager.GetString("newText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        internal static string north {
            get {
                return ResourceManager.GetString("north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all fields are filled in. Fill in all fields and try again..
        /// </summary>
        internal static string notAllFieldFilledIn {
            get {
                return ResourceManager.GetString("notAllFieldFilledIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no notes yet. Create a new note by tapping &apos;new&apos; in the top right corner..
        /// </summary>
        internal static string notesPageNoNotes {
            get {
                return ResourceManager.GetString("notesPageNoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string notesPageTitle {
            get {
                return ResourceManager.GetString("notesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack counting.
        /// </summary>
        internal static string stackCountingPageTitle {
            get {
                return ResourceManager.GetString("stackCountingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string succes {
            get {
                return ResourceManager.GetString("succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The letter was succesfully added..
        /// </summary>
        internal static string succesLetterAdded {
            get {
                return ResourceManager.GetString("succesLetterAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Counted through returns .
        /// </summary>
        internal static string wordValuePageCountedThrough {
            get {
                return ResourceManager.GetString("wordValuePageCountedThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word value.
        /// </summary>
        internal static string wordValuePageTitle {
            get {
                return ResourceManager.GetString("wordValuePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word value is .
        /// </summary>
        internal static string wordValuePageWordValue {
            get {
                return ResourceManager.GetString("wordValuePageWordValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string wordValueWord {
            get {
                return ResourceManager.GetString("wordValueWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your note.
        /// </summary>
        internal static string yourNote {
            get {
                return ResourceManager.GetString("yourNote", resourceCulture);
            }
        }
    }
}
